#+OPTIONS: toc:nil
#+OPTIONS: exports code
* fsklearn

A simple module for machine learning in Fortran using [[https://github.com/scikit-learn/scikit-learn][scikit-learn]].

** Overview

The prediction part, as it may be called frequent by a FORTRAN code, is written with FORTRAN. 

- Currently the module can be used to do training and prediction in FORTRAN. 

- The training part uses [[https://github.com/scikit-learn/scikit-learn][scikit-learn]] library by calling Python from FORTRAN. 

- The prediction part, as it may be called frequent by a FORTRAN code, is written with FORTRAN 2003. 

** Supported machine learning method
Currently, the following methods are supported for
*regression* (not classification) problem:

- Neual Networks
- Decision Tree
- Random Forest


** Supported FORTRAN compiler
    The following compiler are tested. 
- Intel - Tested with 2019.0.2.187
- GNU - Tested with 8.1.0

** Required packages for *Python3*
   - numpy
   - json
   - [[https://github.com/scikit-learn/scikit-learn][scikit-learn]]

** build tool
  - Makefile
  - [[https://github.com/szaghi/FoBiS][FoBis.py]] (testing)
  
** Run the test

  #+BEGIN_SRC sh
  git clone https://github.com/Yeldon/fsklearn.git
  cd fsklearn/
  cp -r tests/src ./
  cp -r tests/build ./
  make 
  ./build/fsklearn_test
  #+END_SRC

** Example
   Assume you have set up the file path and the correct input and output
   interface for your data, a simple main program (sequential version) could be:
   - training
  #+BEGIN_SRC f90
  program main
  use mod_fsklearn
  implicit none
  integer :: input_len = 3
  integer :: input_len = 3
  integer :: num_datalen = 500
  integer :: sample_data(500,6)

  Call fsklearn_initialization ! Initialization
  ! Assume you have defined your interface in mod_fsklearn
  Call F_Sklearn%Fen_Training(sample_data,3, 3, 500)
  Call F_Sklearn%PY_Training ! Call python to train

  end program main
  #+END_SRC

  - prediction
  #+BEGIN_SRC f90
  program main
  use mod_fsklearn
  implicit none
  integer :: inputs = 3

  Call fsklearn_initialization ! Initialization
  inputs=[-0.99,0.141067, -0.54]
  ! If you have setup the mod_fsklearn and input.namelist, this should be working
  F_Sklearn%outputs = F_Sklearn%predict(inputs,F_Sklearn%n_inputs,F_Sklearn%n_outputs)
  #+END_SRC

** Progress[6/8]
  - [X] Glue FORTRAN and Python
  - [X] Basic training and prediction interface
  - [X] MPI version
  - [X] First step tests
  - [X] A more smart Python code generator
  - [X] Parameters for training function 
  - [ ] Prediction for data, vector and matrix
  - [ ] Second step tests 

** License

This project is licensed under the BSD3 - see the [LICENSE.md](LICENSE.md) file for details
